name: main

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'

      - name: Dependencies
        run: npm ci

      - name: Build
      - run: npm run build

      - name: Lint
        run: npm run lint

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./dist
